### ISSUE TITLE
Deck Generator: Fusion Substitute/Polymerization

### ISSUE THREAD

**Issue by Zibokwe** [FelixRilling/yugioh-deck-tool#46]
These cards are treated as the same name, so more than 3 can't exist in total in a deck, but often i see 3 fus sub 3 poly, or 2 poly 2 fus sub, etc. Same would go for harpie lady #1 2 and 3 for example.

**Comment by FelixRilling** [comment]
Good point, with the current card data i can't determine that just yet but ill see if i can fix that.

**Comment by FelixRilling** [comment]
I have the new fields i need in the database now, ill try implementing it soon.

**Comment by FelixRilling** [comment]
This is rather hard for me to test because of the randomness, but it think its fixed now.

**Comment by AlanOC91** [comment]
Issue still occurs when manually entering cards.

It shouldn't occur for both randomize and manual entry. Same applies for alt. artwork cards such as Dark Magician.

**Comment by AlanOC91** [comment]
Found another bug.

If you add x3 Dark Magician then it won't allow you to add any Dark Magician Girl and vice versa. 

Even though Dark Magician treated as is "Dark Magician" and Dark Magician Girl treated as is "Dark Magician Girl"

**Comment by FelixRilling** [comment]
Are you sure you emptied the cache? I cannot reproduce this.

**Comment by AlanOC91** [comment]
Yeah emptied both browser and cloudflare cache and tested with multiple web browsers.

Can only add 3 cards and no more. So I could add 3 different cards and that's it. Example: Time Wizard x1, Dark Magician x1, Pot of Greed x1 and that's it. Can't add any more.

Another user had the issue here: https://ygoprodeck.com/Forum/viewtopic.php?f=21&t=1879

**Comment by FelixRilling** [comment]
Fixed by updating the converter.
